# Generated by Django 3.0.5 on 2020-04-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0005_auto_20200405_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='revibe',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vibe',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revibe',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revibe_original', to='Platform.Vibe'),
        ),
        migrations.AlterField(
            model_name='vibed',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibed_original', to='Platform.Vibe'),
        ),
    ]
