# Generated by Django 3.0.5 on 2020-04-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0006_auto_20200415_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('vibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_vibe', to='Platform.Vibe')),
            ],
        ),
    ]
