# Generated by Django 3.0.5 on 2020-04-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0007_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
