# Generated by Django 3.0.5 on 2020-04-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0009_auto_20200417_0327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vibed',
        ),
    ]
