# Generated by Django 3.0.5 on 2020-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0010_delete_vibed'),
    ]

    operations = [
        migrations.AddField(
            model_name='revibe',
            name='sentiment',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='vibe',
            name='sentiment',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
